import type { Lead } from "./types";

export const SEED_LEADS: Lead[] = [
  {
    id: "lead-1",
    name: "Maya Chen",
    company: "Northwind Labs",
    city: "San Francisco",
    region: "CA",
    country: "US",
    lat: 37.7749,
    lng: -122.4194,
    status: "meeting",
    channel: "Cold email",
    notes: "Interested in Q2 pilot for outbound SDR tooling.",
    createdAt: "2026-09-12T14:20:00.000Z",
  },
  {
    id: "lead-2",
    name: "Jordan Hale",
    company: "Harbor & Co",
    city: "Austin",
    region: "TX",
    country: "US",
    lat: 30.2672,
    lng: -97.7431,
    status: "replied",
    channel: "LinkedIn",
    notes: "Asked for pricing deck — follow up Friday.",
    createdAt: "2026-09-18T10:05:00.000Z",
  },
  {
    id: "lead-3",
    name: "Priya Nair",
    company: "Lumen Retail",
    city: "Chicago",
    region: "IL",
    country: "US",
    lat: 41.8781,
    lng: -87.6298,
    status: "contacted",
    channel: "Cold email",
    notes: "Sent intro sequence day 3.",
    createdAt: "2026-09-22T16:40:00.000Z",
  },
  {
    id: "lead-4",
    name: "Eli Romero",
    company: "Cascade Health",
    city: "Seattle",
    region: "WA",
    country: "US",
    lat: 47.6062,
    lng: -122.3321,
    status: "new",
    channel: "Event",
    notes: "Met at SaaStr — wants a map of regional clinics.",
    createdAt: "2026-09-28T19:15:00.000Z",
  },
  {
    id: "lead-5",
    name: "Sofia Ruiz",
    company: "Brightline Media",
    city: "Miami",
    region: "FL",
    country: "US",
    lat: 25.7617,
    lng: -80.1918,
    status: "contacted",
    channel: "Referral",
    notes: "Intro from Marcus. Agency with LATAM clients.",
    createdAt: "2026-09-30T12:00:00.000Z",
  },
  {
    id: "lead-6",
    name: "Tomás Almeida",
    company: "Orbit Finance",
    city: "New York",
    region: "NY",
    country: "US",
    lat: 40.7128,
    lng: -74.006,
    status: "replied",
    channel: "Cold email",
    notes: "Compliance review before demo.",
    createdAt: "2026-10-01T09:30:00.000Z",
  },
  {
    id: "lead-7",
    name: "Hannah Brooks",
    company: "Fieldstone Ventures",
    city: "Denver",
    region: "CO",
    country: "US",
    lat: 39.7392,
    lng: -104.9903,
    status: "new",
    channel: "LinkedIn",
    notes: "Portfolio ops lead — maps LP outreach.",
    createdAt: "2026-10-02T15:45:00.000Z",
  },
  {
    id: "lead-8",
    name: "Kenji Sato",
    company: "Nimbus Cloud",
    city: "Boston",
    region: "MA",
    country: "US",
    lat: 42.3601,
    lng: -71.0589,
    status: "closed",
    channel: "Cold email",
    notes: "Chose competitor — keep warm for renewals.",
    createdAt: "2026-08-20T11:10:00.000Z",
  },
  {
    id: "lead-9",
    name: "Amelia Grant",
    company: "Cedar Studio",
    city: "London",
    region: "England",
    country: "GB",
    lat: 51.5074,
    lng: -0.1278,
    status: "meeting",
    channel: "Event",
    notes: "EU expansion interest. Demo booked Oct 10.",
    createdAt: "2026-10-03T08:20:00.000Z",
  },
  {
    id: "lead-10",
    name: "Luis Ortega",
    company: "Mercado Norte",
    city: "Mexico City",
    region: "CDMX",
    country: "MX",
    lat: 19.4326,
    lng: -99.1332,
    status: "contacted",
    channel: "Referral",
    notes: "Spanish outreach sequence started.",
    createdAt: "2026-10-04T17:00:00.000Z",
  },
];
